version: '3'

services:
  database_template:
    image: postgres
    container_name: database_template
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mudar1234
      - POSTGRES_DB=template
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: template
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/brycpt/
    links: 
      - database_template
    depends_on:
      - database_template

volumes:
  pgdata:
    driver: local